name: 01 Basics First Workflow
run-name: ${{github.actor}} explain-context-data

env:
  RUN_NUMBER: ${{ github.run_number >= 1 && 'greater than 1' || 'less than 1' }}
  
on:  
  workflow_dispatch

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    env: 
      MY_NAME2: 'Abdallah wael 2'
    steps:
      - name: Print steps vars
        env:
          MY_NAME3: 'Abdallah Wael3'
        # run: echo ${{to_json(github)}}
        # run: echo ${{to_json(github.event)}}
        # run: echo ${{github.actor}}
        run: echo ${{env.RUN_NUMBER}}
        
      - name: Print job vars
        run: echo ${{env.MY_NAME2}}

      - name: Print config vars
        run: echo ${{vars.MY_CONFIG_VALUE}}

      - name: Print secret vars
        run: echo ${{secrets.MY_CREDENTIAL_PASS }}

  Build: 
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: echo "hello world"

  Test: 
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Build Project
        run: echo "Test Project Dependency"
  Deploy: 
    runs-on: ubuntu-latest
    needs: [Build,Test]
    steps:
      - name: Build Project
        run: echo "Deploy Project Dependency"



