name: Basics Github cli
run-name: ${{github.actor}} explain-Github cli
  
on:  
  workflow_dispatch

jobs:
  open-new-issue-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.3
        
      - name: Open New Issue
        run: gh issue create --title "New Issue from Github Actions" --body "Nothing Works"

        env:
            GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
